version: 2
jobs:

  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Jason
          command: |
            make install-dev
      - run:
          name: Check Source Code
          command: |
            make check
      - run:
          name: Run Unit Tests
          command: |
            make test

workflows:
  version: 2
  test:
    jobs:
      - test
