version: 2
jobs:

  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Jason
          command: |
            make install-dev
      - run:
          name: Check Source Code
          command: |
            make lint
      - run:
          name: Run Unit Tests
          command: |
            make test

  dependency-check:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Create Egg Info
          command: python3 setup.py egg_info
      - run:
          name: Check Dependencies
          command: ./scripts/check_dependencies.sh

  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Create dist
          command: python3 setup.py sdist
      - run:
          name: Upload to gemfury
          command: ./scripts/gem_fury_deploy.sh dist/$(ls dist | sort -nr | head -1)

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
#      - dependency-check:
#          filters:
#            branches:
#              only:
#                - master
#                - develop
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
